### ISSUE TITLE
Spieler Ruckelt wenn AFK und in Wasser/Fall etc. [BUG]

### ISSUE THREAD

**Issue by PhilipU** [raidcraft/rcskills#43]
Wenn ein AFK Spieler knapp an der Kante zum Wasser steht und dort riengeschubst wird oder selbst dort reinläuft, fängt er an zu ruckeln, da das Move Event gecancelt wird.
Das kostet vermutlich auch Performance.
Evtl. ist es einfacher den Spieler in den Spectator Modus zu versetzen oder ihm ihn fliegen zu lassen, so dass er schwebt.

**Comment by Silthus** [comment]
Das ist tatsächlich nix von RCSkills sondern wird von Essentials gehandelt. Habe da gestern die freeze flag eingestellt damit Spieler nicht geschubst werden können.
Aber vielleicht drehen wir das wieder ab und schalten lieber Kollision auf dem Mainserver aus.
