### ISSUE TITLE
Skill mit Konfiguration 'hidden' wird auch nach Config-Änderung nicht mehr sichtbarBUG]

### ISSUE THREAD

**Issue by PhilipU** [raidcraft/rcskills#55]
In der rcs_skills Tabelle bleibt die Hidden Flag immer auf 1 und der Skill taucht nicht mehr in der Spieler Übersicht auf.
Nur ein manuelles löschen der Flag und rcs reload hilft

**Comment by Silthus** [comment]
Wird mit #54 behoben.
